'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RtpLabTestDone
    
    '''<summary>
    '''Hddid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hddid As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''filter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filter As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbltestdone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltestdone As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Lbldiagnosis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbldiagnosis As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbodiagnosis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbodiagnosis As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Btnsearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btnsearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Lnkfrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnkfrom As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Calfrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Calfrom As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtfrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Lnkto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnkto As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Calto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Calto As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''Txtto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''nodata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nodata As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''grdrequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdrequest As Global.System.Web.UI.WebControls.GridView
End Class
